#!/usr/bin/env bash
########################################
# Add a birthday to the birthdays file # 
#                                      #
# Firstname   Surname    Day    Month  #
########################################

# TODO check date is valid

while getopts "f:s:d:m:" opt; do
    case ${opt} in
        f )
            fname=$OPTARG
            ;;
        s )
            sname=$OPTARG
            ;;
        d )
            day=$OPTARG
            ;;
        m )
            month=$OPTARG
    esac
done

if [ ! -f birthdays ] 
then
    touch birthdays
fi



row="$fname,$sname,$day,$month"

sed -i "/$row/d" birthdays # remove matching lines to prevent duplicates

echo $row >> birthdays
